### ISSUE TITLE
Could not find skip and sort.

### ISSUE THREAD

**Issue by agozie** [HouzuoGuo/tiedot#89]
I want to use tiedot in a project but I also need to paginate results. I could not find examples of limit, skip or sort in the documentation. Are they implemented or are there practical workarounds?

**Comment by HouzuoGuo** [comment]
Due to the lack of a suitable index implementation for range queries, sorting and pagination are not supported in general.
I have failed in several attempts at creating an index for range queries, very sorry about that.

tiedot has good throughput in general, therefore, try to implement paging on the application server, it may still yield satisfactory performance.

**Comment by agozie** [comment]
The performance is very good, as advertised, I inserted 1 million records in 5 secs. How safe is my data, in terms of corruption? and must I call srub()?

**Comment by HouzuoGuo** [comment]
Good to know!

A hard crash usually does not corrupt data files, but if it does in an unlikely event, tiedot will notify you by log messages.

Scrub is not necessary unless you wish to save some disk space by compacting the DB, or if data corruption has been noticed.

**Comment by HouzuoGuo** [comment]
I'm closing this one for now, feel free to come back anytime
