### ISSUE TITLE
Persistent / clustering feature request

### ISSUE THREAD

**Issue by vadimyer** [HouzuoGuo/tiedot#92]
Hi,

Very promising project! I like the idea it's totally powered by Go. And already guess this is a in-memory NoSQL db best used as embedded.
Are there any plans for persistent storage as well as clustering? Also I think it would be a good idea to have an option to have an SSD as a storage, but memory for indexes only (like in Redis).

**Comment by HouzuoGuo** [comment]
Hello Vadimyer.

tiedot uses memory for caching and it is a persistent document database. Databases are persistent on disk at all time.

However there is a very small chance of data loss in case of a DB or OS crash due to lack of a journal. The data structures are crash-resilient to ensure the maximum availability of the remaining data.

tiedot aims for vertical scalability instead of horizontal scalability. The development branch "singlethread" (bad name) has shown very promising and near-perfect scalability:

https://github.com/HouzuoGuo/tiedot/blob/singlethread/extra/suse-hackweek-12.pdf

I just need to find some time to finish it up.

**Comment by HouzuoGuo** [comment]
I hope that answers your question. If you need anything else feel free to ask!
