### ISSUE TITLE
Close() in embedded

### ISSUE THREAD

**Issue by techjanitor** [HouzuoGuo/tiedot#93]
Is there a standard way to call Close() in an embedded program on shutdown?

Should I be watching signal.Notify, or is there an easier way to handle it. My programs are usually handled by supervisord or systemd, which just calls sigterm IIRC. I don't have a shutdown function like in your httpapi implementation.

**Comment by HouzuoGuo** [comment]
Feel free to call database.Close():
https://github.com/HouzuoGuo/tiedot/blob/master/db/db.go#L84
Just remember to get rid of references to database after it is closed. Continuing using a database after it is closed will cause crash due to memory fault.

It is a good practice to catch interrupt/terminate signal and call database.Close() in the signal handler.

**Comment by HouzuoGuo** [comment]
feel free to come back when you need anything!
